### ISSUE TITLE
Output Problem

### ISSUE THREAD

**Issue by HarryXD2018** [AnshulSood11/Engagement-Level-Prediction#3]
Hello, I have executed the python and modified OpenFace for more than 20 minutes, but there was nothing but a blank plot window with axes.  
Should I wait for more samples to be extracted? Or there is something wrong when I installed it.
Please help me out, thanks.

**Comment by AnshulSood11** [comment]
Hi,
First run the OpenFace code and then `predict.py`. Wait for 10 seconds and then matplotlib should start plotting. If you feel you have followed all the steps in the [Getting Started](https://github.com/AnshulSood11/Engagement-Level-Prediction#geting-started) section correctly then paste here whatever output you are getting in your `predict.py` terminal.

**Comment by HarryXD2018** [comment]
Thank you so much for replying! It turns out that at line 85 in `predict.py`, we made a mistake about the relative path and it is cool when we replace it with the absolute path, so do the following lines contain paths.
