### ISSUE TITLE
Categories classification

### ISSUE THREAD

**Issue by atoaiari** [AnshulSood11/Engagement-Level-Prediction#4]
Hi, how the values ​​were chosen to classify the categories? Why not 0, 0.33, 0.66 and 1?

Thank you!

**Comment by AnshulSood11** [comment]
Hi, thanks for your interest.

These values were chosen empirically. 

For example, when I was clearly looking away from the screen, the intensity values were consistently closer to 0.4. So I increased the upper bound for Disengaged category to 0.4. Similarly other values were chosen as they seemed to be categorizing correctly.

**Comment by atoaiari** [comment]
Thank you for the answer, very useful. 
What about the dataset? Would it be possible to have the link for downloading it?

**Comment by AnshulSood11** [comment]
I had used pre-trained models provided by [this](https://github.com/th2l) guy.

You may refer to his research [here](https://www.researchgate.net/publication/336626637_Engagement_Intensity_Prediction_withFacial_Behavior_Features) where he mentions using "Engagement in the wild dataset" which I was also not able to find.

If you are training your own model [this](https://iith.ac.in/~daisee-dataset/) dataset might be helpful.

**Comment by atoaiari** [comment]
Thank you! I can close this issue.
